### ISSUE TITLE
files opened with :Files are not showing syntax highlighting and :Buffers is not showing preview correctly

### ISSUE THREAD

**Issue by zzzeyez** [LoricAndre/fzterm.nvim#11]
this is with defaults on macos with the latest version of all components.  `bat` and `rg` are installed via homebrew

also, on macos, rg spits out errors about accessing stuff in ~/library

<img width="1113" alt="10-20-59" src="https://user-images.githubusercontent.com/24757574/98019157-a853fb80-1dbe-11eb-83ae-7e06049c4bc2.png">

<img width="548" alt="10-41-44" src="https://user-images.githubusercontent.com/24757574/98021226-4c3ea680-1dc1-11eb-9f26-50468fc4dd1b.png">

it might be worth noting that these issues persist when disabling `treesitter` and that the `bat` preview works perfectly for `:Files`

**Comment by LoricAndre** [comment]
Hi,
firstly the `rg` error probably isn't coming from my end, it will probably happen too if you try to run rg manually in your home (But I do agree that fzf handles it poorly).
The issue on the first screenshot should be fixed in the last commit.

**Comment by zzzeyez** [comment]
i'm on the latest commit and both issues persist

and to be clear: the first screenshot features two separate issues that are both listed in the title

**Comment by LoricAndre** [comment]
Alright, sry for reading the issue too fast. The 2 issues should be fixed now, can you check it out pls ?

**Comment by zzzeyez** [comment]
syntax highlighting is now functioning correctly after opening with `:Files`

`:Buffers` works correctly now, although it requires confirmation before opening and shows multiple ghost buffers

<img width="766" alt="17-27-41" src="https://user-images.githubusercontent.com/24757574/98055195-21bd0f80-1dfa-11eb-973c-4a883533af9b.png">

**Comment by zzzeyez** [comment]
actually the `:Buffers` issue remains as a whole in some instances.  it seems the lua files were displaying fine, but these .zsh files are not

**Comment by LoricAndre** [comment]
All right, the ghost buffers are an issue I should have worked on a while ago sry ^^. For the preview of the term buffers, it won't be fixed since they cannot be accessed by any command I could run in the terminal.

**Comment by LoricAndre** [comment]
Sorry I didn't see your last comment, can you pls open a new issue with steps to reproduce and screenshots ?

**Comment by zzzeyez** [comment]
here is a video of me using the plugin with defaults

![nvim2](https://user-images.githubusercontent.com/24757574/98142795-81acc800-1e85-11eb-9839-b88592bd47b6.gif)

everything is newest version.  the issues with `rg` are possibly on my side and you can ignore them.  i'll be using `fd` anyways

**Comment by LoricAndre** [comment]
I see nothing wrong with the plugin here : 
 - The messages during fzf loading are due to you not having permission on some files in your home, which seems to be your `pwd`
 - The display issues on the terminal buffers are normal and cannot be solved as stated earlier
 - The error when exiting the floating window has been reported in issue #13 and is due to an outdated version of neovim.
